[package]
name = "a3s-ash"
description = "AI Native Shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "ash"
path = "src/main.rs"

[features]
default = ["human-shell"]
human-shell = ["dep:ash-shell"]

[dependencies]
ash-engine.workspace = true
ash-ops.workspace = true
ash-platform.workspace = true
ash-protocol.workspace = true
ash-shell = { workspace = true, optional = true }
ash-store.workspace = true
ash-update.workspace = true
futures.workspace = true
reqwest.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
blake3.workspace = true
serde_json.workspace = true
sha2.workspace = true
