[package]
name = "a3s-ash-shell"
description = "Portable human-shell syntax, state, execution, and interaction for ash"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
ash-ops.workspace = true
ash-platform.workspace = true
rustyline.workspace = true
tokio.workspace = true
